apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: helm-mgmt
  name: helm-robot
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods", "deployments"]
  verbs: ["get", "watch", "list"]
