apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  {{- with .Values.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end}}
  name: {{ .Release.Name }}-{{ .Values.api_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.authorization }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.api_name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.api_name }}
    spec:
      containers:
        - name: api
          image: {{ .Values.image.url }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
{{- with .Values.container_ports }}
{{ tpl . $ | indent 12 }}
{{- end }}
          env:
{{- with .Values.the_env }}
{{ tpl . $ | indent 12 }}
{{- end }}
        - name: {{ .Release.Name }}-cloudsql-proxy
          image: {{ .Values.image.url }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end}}
          securityContext:
            runAsUser: {{ .Values.securityContext.user }}
            allowPrivilegeEscalation: {{ .Values.securityContext.escalation }}
          volumeMounts:
{{- with .Values.the_volumeMounts }}
{{ tpl . $ | indent 10 }}
{{- end }}
      volumes:
{{- with .Values.volumes }}
{{ tpl . $ | indent 8 }}
{{- end }}
