apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: helm-mgmt
  name: tiller-mgmt-admin
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
